#!/bin/bash


if [[ $1 != "noReplot" ]]; then
	cd data
	python giaModel.py
	cd ../
fi
## noReplot can be passed to skip regenerating all of the graphs,
## giaModel.py has gotten a bit bloated in terms of runtime
printf "\n\n################################################################################\n"
printf "## Generating Presentation PDF... ##############################################\n"
printf "################################################################################\n\n"

pdflatex giaPres.tex

printf "\n\n################################################################################\n"
printf "## Generating Paper PDF... #####################################################\n"
printf "################################################################################\n\n"

pdflatex gia.tex

printf "\n\n################################################################################\n"
printf "## Generating Abstract PDF... ##################################################\n"
printf "################################################################################\n\n"

pdflatex outstract.tex


exit 0
